version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: wallet_postgres
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql  # ВАЖНО: для Pg18 не /var/lib/postgresql/data, а /var/lib/postgresql 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet_user -d wallet_db"]
      interval: 3s
      timeout: 3s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:8.2.2
    container_name: wallet_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAYGROUND:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAYGROUND://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REREPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAYGROUND://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  redis:
    image: redis:8.0-alpine
    container_name: wallet_redis
    ports:
      - "6379:6379" 

volumes:
  pgdata:
