syntax = "proto3";

package wallet;

// Обязательно указываем полный путь, куда сгенерировать Go-код
option go_package = "github.com/aimv/gopher-wallet-monorepo/wallet-service/pkg/walletgrpc";

// Описываем gRPC сервис
service WalletService {
  rpc GetBalance(GetBalanceRequest) returns (GetBalanceResponse);
}

// Структура входящего запроса
message GetBalanceRequest {
  string user_id = 1;
}

// Структура исходящего ответа
message GetBalanceResponse {
  string wallet_id = 1;
  int64 balance = 2;
  string status = 3; // 'ACTIVE' или 'BLOCKED'
  string currency = 4;
}