// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/aimv/gopher-wallet-monorepo/wallet-service/internal/delivery/http"
	"github.com/aimv/gopher-wallet-monorepo/wallet-service/internal/repository"
	"github.com/aimv/gopher-wallet-monorepo/wallet-service/internal/usecase"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Injectors from wire.go:

// InitializeApplication собирает все зависимости в готовый HTTP-хендлер
func InitializeApplication(ctx context.Context, pool *pgxpool.Pool, kafkaBroker string) (*http.Handler, error) {
	walletRepository := repository.NewWalletRepository(pool)
	kafkaPublisher := repository.NewKafkaPublisher(kafkaBroker)
	walletUseCase := usecase.NewWalletUseCase(walletRepository, kafkaPublisher)
	handler := http.NewHandler(walletUseCase)
	return handler, nil
}
